#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


# Redirect output to stderr.
exec 1>&2



#array=`git diff-index --name-only HEAD`
array=`git diff --cached --name-only HEAD`

./pypre-commit ${array}

